name: Generate Neothesia Video

on:
  workflow_dispatch:

jobs:
  build-and-generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install FFmpeg dev libraries and pkg-config
        run: sudo apt-get update && sudo apt-get install -y pkg-config libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev libgl1 libglx-mesa0 libgl1-mesa-dri mesa-utils fluidsynth      
      - name: Clone Neothesia
        run: git clone https://github.com/PolyMeilex/Neothesia.git

      - name: Build neothesia-cli
        run: cargo build --release -p neothesia-cli
        working-directory: ./Neothesia/neothesia-cli

      - name: Download MIDI file
        run: wget -O mozart_sonata_545_1.mid "https://www.kunstderfuge.com/-/midi.asp?file=mozart/piano_sonata_545_1_(c)oguri.mid"

      - name: Convert MIDI to WAV
        run: fluidsynth -ni ./Neothesia/default.sf2 mozart_sonata_545_1.mid -F output.wav

      - name: Show current directory and files
        run: |
          pwd
          ls -l
          tree ./Neothesia/target/release

      - name: Generate video from MIDI
        run: ./Neothesia/target/release/neothesia-cli mozart_sonata_545_1.mid

      - name: join audio
        run: ffmpeg -i ./out/video.mp4 -i output.wav -c:v copy -c:a libmp3lame -q:a 2 -map 0:v:0 -map 1:a:0 outputvid.mp4

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: neothesia-video
          path: outputvid.mp4
