name: midi2wav

on:
  workflow_dispatch:

jobs:
  build-and-generate-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FluidSynth
        run: sudo apt-get update && sudo apt-get install -y fluidsynth midisox

      - name: Clone Neothesia
        run: git clone https://github.com/PolyMeilex/Neothesia.git

     # - name: Download MIDI file
     #   run: wget -O mozart_sonata_545_1.mid "https://www.kunstderfuge.com/-/midi.asp?file=mozart/piano_sonata_545_1_(c)oguri.mid"

      - name: Concatenate MIDI files
        run: |
          mkdir -p output
          # Concatenate all .mid files in the midis/ folder, adjust path as needed
          midisox -s midis/*.mid output/concatenated.mid




      - name: Convert MIDI to WAV
        run: fluidsynth -ni ./Neothesia/default.sf2 output/concatenated.mid -F output.wav

      - name: Show current directory and files
        run: |
          pwd
          ls -l
          # tree ./Neothesia/target/release

      - name: Upload audio artifact
        uses: actions/upload-artifact@v4
        with:
          name: neothesia-audio
          path: output.wav
